// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TesteCAPGEMINI.Models;

public partial class Pedido
{
    [Key]
    public int Id { get; set; }

    [DisplayName("Id do Cliente")]
    public int IdCliente { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    [DisplayName("Nome do Cliente")]
    public string NomeCliente { get; set; }

    [DisplayName("Id do Produto")]
    public int IdProduto { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    [DisplayName("Nome do Produto")]
    public string NomeProduto { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    [DisplayName("Endereço de Entrega")]
    public string EnderecoEntrega { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? PrecoTotal { get; set; }

    [ForeignKey("IdCliente")]
    [InverseProperty("Pedidos")]
    public virtual Cliente IdClienteNavigation { get; set; }

    [ForeignKey("IdProduto")]
    [InverseProperty("Pedidos")]
    public virtual Produto IdProdutoNavigation { get; set; }
}