// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TesteCAPGEMINI.Models;

public partial class Pedido
{
    [Key]
    public int Id { get; set; }

    public int IdCliente { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeCliente { get; set; }

    public int IdProduto { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeProduto { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string EnderecoEntrega { get; set; }

    public int PrecoTotal { get; set; }

    [ForeignKey("IdCliente")]
    [InverseProperty("Pedidos")]
    public virtual Cliente IdClienteNavigation { get; set; }

    [ForeignKey("IdProduto")]
    [InverseProperty("Pedidos")]
    public virtual Produto IdProdutoNavigation { get; set; }
}