// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TesteCAPGEMINI.Models;

public partial class Produto
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("Faixa Etária")]
    public string Idade { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Peso { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Linha { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Pet { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    [DisplayName("Porte da Raça")]
    public string PorteRaca { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Sabor { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    [DisplayName("Preço")]
    public string Preco { get; set; }

    [InverseProperty("IdProdutoNavigation")]
    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
}